.eslintrc.cjs, .github/workflows/main.yml, apps/auth/src/auth.resolver.ts, apps/auth/src/main.ts, apps/auth/test/app.e2e-spec.ts, package.json, webpack.config.js, yarn.lock
=> 5 create ci configuration

.dockerignore, .eslintrc.cjs, .gitignore, .prettierignore, package.json, stryker.conf.mjs, yarn.lock
=> 9 configurate stryker

.eslintrc.cjs, apps/auth/src/auth.module.ts, apps/auth/test/jest-e2e.json, tsconfig.json
=> chore: change alias `@app/common` -> `@lib/common`

.eslintrc.cjs, apps/auth/src/strategies/jwt.strategy.ts, apps/auth/src/strategies/spotify.strategy.ts, apps/auth/src/types/spotify-auth.ts, apps/auth/test/jest-e2e.json, apps/statistics/test/jest-e2e.json, jest.config.ts, tsconfig.json
=> 28 create aliases for apps

apps/statistics/src/statistics.resolver.spec.ts, apps/statistics/src/statistics.resolver.ts, apps/statistics/src/statistics.service.ts
=> feat(statistics): create `limit` argument

apps/statistics/src/dtos/index.ts, apps/statistics/src/dtos/limit.dto.ts, apps/statistics/src/main.ts, apps/statistics/src/statistics.resolver.spec.ts, apps/statistics/src/statistics.resolver.ts, package.json, yarn.lock
=> 42 statisticsmodule implement validation max on limit argument

.vscode/settings.json
=> chore(config): add `.vscode/settings`

apps/auth/src/auth.module.ts, apps/player/src/player.module.ts, apps/statistics/src/statistics.module.ts
=> 55 enable playground for production

docs/README.md
=> docs(docs/README): update `auth` microservice endpoints and dtos

apps/auth/src/auth.controller.spec.ts, apps/auth/src/auth.controller.ts, apps/auth/src/auth.resolver.spec.ts, apps/auth/src/auth.resolver.ts
=> fix(auth): save secure tokens as httpOnly and secure cookie

dist/main.js, src/common/mocks/artist.mock.ts, src/modules/adapter/adapter.service.ts, src/modules/statistics/statistics.service.ts
=> 74 fix top elements external links

src/modules/statistics/decorators/api-item-query.decorator.ts, src/modules/statistics/decorators/index.ts, src/modules/statistics/dtos/index.ts, src/modules/statistics/dtos/item-query.dto.ts, src/modules/statistics/dtos/limit-query.dto.ts, src/modules/statistics/dtos/top-item-query.dto.ts, src/modules/statistics/statistics.controller.ts, src/modules/statistics/statistics.service.ts
=> 98 implement pagination for statistics

.github/workflows/main.yml, .vscode/settings.json, src/modules/auth/auth.controller.spec.ts, src/modules/auth/auth.controller.ts, src/modules/images/images.repository.spec.ts, src/modules/images/images.repository.ts, src/modules/profiles/profile.entity.ts, src/modules/profiles/profiles.repository.spec.ts, src/modules/profiles/profiles.repository.ts, src/modules/profiles/profiles.service.spec.ts, src/modules/profiles/profiles.service.ts, src/modules/users/user.entity.ts, src/modules/users/users.controller.spec.ts, src/modules/users/users.controller.ts, src/modules/users/users.repository.spec.ts, src/modules/users/users.repository.ts, tsconfig.json
=> 115 refactor repositories

src/modules/users/users-profile.controller.spec.ts, src/modules/users/users-profile.controller.ts
=> feat(modules/users-profile.controller): add `getAnalysis` method`

src/common/mocks/axios-response.factory.mock.ts, src/common/utils/catch-spotify-error.spec.ts, src/common/utils/catch-spotify-error.ts
=> refactor(common/utils/catch-spotify-error): add typings

src/modules/auth/auth.controller.ts, src/modules/player/player.controller.ts, src/modules/statistics/statistics.controller.ts, src/modules/users/user.entity.ts, src/modules/users/users-profile.controller.ts, src/modules/users/users.controller.spec.ts, src/modules/users/users.controller.ts
=> docs(modules/controller): add missing documentation

src/modules/albums/albums.repository.spec.ts, src/modules/albums/albums.repository.ts, src/modules/artists/artists.controller.spec.ts, src/modules/artists/artists.controller.ts, src/modules/tracks/tracks.repository.spec.ts, src/modules/tracks/tracks.repository.ts
=> 180 fix queryfailederror duplicate key value violates unique constraint uq d9c245cc24c616be9b5d72900f5

src/modules/albums/albums.repository.spec.ts, src/modules/albums/albums.repository.ts, src/modules/artists/artists.controller.spec.ts, src/modules/artists/artists.controller.ts, src/modules/spotify/albums/spotify-albums.service.ts, src/modules/spotify/artists/spotify-artists.service.ts, src/modules/spotify/constants.ts, src/modules/spotify/tracks/spotify-tracks.service.ts, src/modules/tracks/tracks.repository.spec.ts, src/modules/tracks/tracks.repository.ts
=> 181 fetch max 20 items at the time in spotify services

package.json, src/modules/history/history.scheduler.ts, src/modules/spotify/albums/spotify-albums.service.ts, src/modules/spotify/artists/spotify-artists.service.ts, src/modules/spotify/auth/spotify-auth.service.ts, src/modules/spotify/player/spotify-player.service.ts, src/modules/spotify/tracks/spotify-tracks.service.ts, src/modules/spotify/users/spotify-users.service.ts, yarn.lock
=> 182 wrap spotify service methods with backoff

package.json, src/migrations/1711444943012-change-unique-constraints-for-entities.ts, src/migrations/all.ts, src/modules/albums/album.entity.ts, src/modules/artists/artist.entity.ts, src/modules/images/image.entity.ts, src/modules/spotify/albums/spotify-albums.service.ts, src/modules/spotify/artists/spotify-artists.service.ts, src/modules/spotify/auth/spotify-auth.service.ts, src/modules/spotify/player/spotify-player.service.ts, src/modules/spotify/tracks/spotify-tracks.service.ts, src/modules/spotify/users/spotify-users.service.ts, src/modules/tracks/track.entity.ts, yarn.lock
=> 191 change entities unique constraints

src/modules/albums/albums.repository.spec.ts, src/modules/albums/albums.repository.ts
=> fix(modules/albums/repository): `findOrCreateAlbumsFromExternalIds`

src/modules/albums/albums.controller.ts, src/modules/artists/artists.controller.ts, src/modules/tracks/tracks.controller.ts
=> 201 remove authentication need for items controllers

src/modules/history/history.service.ts, src/modules/history/tracks/history-tracks.service.ts
=> 205 fix fetching user history

src/modules/auth/auth.service.spec.ts, src/modules/auth/auth.service.ts, src/modules/history/history.scheduler.spec.ts, src/modules/history/history.scheduler.ts, src/modules/history/history.service.spec.ts, src/modules/history/history.service.ts, src/modules/users/controllers/users-history.controller.spec.ts, src/modules/users/controllers/users-history.controller.ts, src/modules/users/users.module.ts
=> 230 history synchronization after get history

src/common/constants/api-messages.ts, src/modules/history/history.service.spec.ts, src/modules/history/history.service.ts, src/modules/history/tracks/history-tracks.service.spec.ts, src/modules/history/tracks/history-tracks.service.ts, src/modules/users/controllers/users-history.controller.spec.ts, src/modules/users/controllers/users-history.controller.ts, src/modules/users/controllers/users-playback.controller.ts, src/modules/users/controllers/users-profile.controller.ts, src/modules/users/controllers/users.controller.ts
=> 234 fix saving new items do database

src/modules/auth/auth.controller.spec.ts, src/modules/auth/auth.controller.ts, src/modules/auth/auth.service.spec.ts, src/modules/auth/auth.service.ts, src/modules/history/history.service.spec.ts, src/modules/history/history.service.ts, src/modules/items/items.service.spec.ts, src/modules/items/items.service.ts, src/modules/items/tracks/track.subscriber.spec.ts, src/modules/items/tracks/track.subscriber.ts, src/modules/items/tracks/tracks.service.spec.ts, src/modules/items/tracks/tracks.service.ts, src/modules/spotify/albums/spotify-albums.service.ts, src/modules/spotify/artists/spotify-artists.service.ts, src/modules/spotify/auth/spotify-auth.service.ts, src/modules/spotify/index.ts, src/modules/spotify/spotify.module.ts, src/modules/spotify/spotify.service.ts, src/modules/spotify/tracks/spotify-tracks.service.ts, src/modules/users/controllers/users-playback.controller.spec.ts, src/modules/users/controllers/users-playback.controller.ts, src/modules/users/controllers/users-profile.controller.spec.ts, src/modules/users/controllers/users-profile.controller.ts
=> 220 refactor spotify items services

src/modules/items/albums/albums.repository.ts, src/modules/items/tracks/tracks.repository.ts
=> fix(modules/items): show track artists in album

src/common/mocks/album.mock.ts, src/modules/items/albums/albums.validator.spec.ts, src/modules/items/albums/albums.validator.ts
=> fix(modules/items/albums/validator): getting sdk album

src/modules/history/history.module.ts, src/modules/history/history.scheduler.spec.ts, src/modules/history/history.scheduler.ts, src/modules/history/utils/index.ts, src/modules/history/utils/synchronize-job-id.factory.util.spec.ts, src/modules/history/utils/synchronize-job-id.factory.util.ts, src/modules/users/controllers/users-history.controller.spec.ts, src/modules/users/controllers/users-history.controller.ts
=> 297 save some jobs for metrics

src/config/database/typeorm.config.ts, src/migrations/1717744803994-enable-cache.ts, src/migrations/all.ts, src/modules/history/history.processor.spec.ts, src/modules/history/history.processor.ts, src/modules/items/albums/albums.controller.ts, src/modules/items/artists/artists.controller.ts, src/modules/items/constants.ts, src/modules/items/tracks/tracks.controller.ts, src/modules/items/tracks/tracks.service.spec.ts, src/modules/items/tracks/tracks.service.ts, src/modules/users/controllers/users-history.controller.ts
=> 293 use typeorm cache

src/common/mocks/page.factory.mock.ts, src/modules/spotify/albums/spotify-albums.service.spec.ts, src/modules/spotify/albums/spotify-albums.service.ts, src/modules/spotify/artists/spotify-artists.service.spec.ts, src/modules/spotify/artists/spotify-artists.service.ts, src/modules/spotify/player/spotify-player.service.spec.ts, src/modules/spotify/tracks/spotify-tracks.service.spec.ts, src/modules/spotify/tracks/spotify-tracks.service.ts, src/modules/spotify/users/spotify-users.service.spec.ts, src/modules/spotify/users/utils/analysis.factory.spec.ts, src/modules/spotify/users/utils/audio-features.reducer.spec.ts, src/modules/spotify/utils/index.ts, src/modules/spotify/utils/split-into-chunks.util.spec.ts, src/modules/spotify/utils/split-into-chunks.util.ts
=> 270 find way to mock nested class module properties with vitest

src/modules/items/artists/controller/artists.controller.spec.ts, src/modules/items/artists/controller/artists.controller.ts, src/modules/items/artists/controller/dtos/artist-top-tracks-query.dto.ts, src/modules/items/artists/controller/dtos/index.ts
=> 309 limit query on top-tracks artist endpoint

src/modules/items/artists/artist.entity.ts, src/modules/items/artists/constants.ts, src/modules/items/artists/controller/artists.controller.spec.ts, src/modules/items/artists/controller/artists.controller.ts, src/modules/items/artists/controller/decorators/api-artist.decorator.ts, src/modules/items/artists/controller/decorators/index.ts, src/modules/items/artists/controller/docs/artist-albums.doc.ts, src/modules/items/artists/controller/docs/artist-top-tracks.doc.ts, src/modules/items/artists/controller/docs/index.ts, src/modules/items/items.service.spec.ts, src/modules/items/items.service.ts, src/modules/spotify/artists/spotify-artists.service.spec.ts, src/modules/spotify/artists/spotify-artists.service.ts, src/modules/users/controllers/users-profile.controller.spec.ts
=> 296 add artistsidalbums endpoint

src/modules/stats/router/stats-router.module.ts, src/modules/stats/router/stats-spotify.controller.spec.ts, src/modules/stats/router/stats-spotify.controller.ts, src/modules/users/controllers/users-profile.controller.ts
=> 326 move spotify top items top stats module

src/modules/stats/router/docs/rigtch-top-albums.doc.ts, src/modules/stats/router/docs/rigtch-top-artists.doc.ts, src/modules/stats/router/docs/rigtch-top-genres.doc.ts, src/modules/stats/router/docs/rigtch-top-tracks.doc.ts, src/modules/stats/router/stats-rigtch.controller.ts, src/modules/stats/stats-rigtch.service.spec.ts, src/modules/stats/stats-rigtch.service.ts, src/modules/stats/types/top-item.type.ts
=> feat: rename playtime -> playTime

src/common/mocks/context.factory.mock.ts, src/common/mocks/user.mock.ts, src/migrations/1721641599620-add-created-at-column-to-user-entity.ts, src/migrations/all.ts, src/modules/stats/router/guards/index.ts, src/modules/stats/router/guards/time-range.guard.spec.ts, src/modules/stats/router/guards/time-range.guard.ts, src/modules/stats/router/stats-rigtch.controller.ts, src/modules/users/constants/index.ts, src/modules/users/dtos/create-user.dto.ts, src/modules/users/user.entity.ts
=> 335 disable rigtch statistics for new users

src/modules/history/router/history.controller.ts, src/modules/stats/router/stats-rigtch.controller.ts, src/modules/stats/router/stats-spotify.controller.ts, src/modules/users/controllers/users-playback.controller.ts, src/modules/users/controllers/users-profile.controller.ts, src/modules/users/controllers/users.controller.ts, src/modules/users/guards/index.ts, src/modules/users/guards/validate-user-id.guard.spec.ts, src/modules/users/guards/validate-user-id.guard.ts
=> refactor(modules/users/guards): rename `CheckUserIdGuard` -> `ValidateUserIdGuard`

src/common/options/default-backoff.options.ts, src/common/options/index.ts, src/common/utils/catch-spotify-error.ts, src/modules/history/history.processor.spec.ts, src/modules/history/history.processor.ts, src/modules/spotify/auth/spotify-auth.service.ts
=> 359 handle revoked token error

src/modules/history/history.module.ts, src/modules/history/history.processor.spec.ts, src/modules/history/history.processor.ts, src/modules/history/history.service.spec.ts, src/modules/history/history.service.ts, src/modules/history/index.ts
=> refactor(modules/history): move synchronize logic to `HistoryService`

src/modules/app/app.module.ts, src/modules/history/tracks/history-tracks.repository.spec.ts, src/modules/history/tracks/history-tracks.repository.ts, src/modules/reports/index.ts, src/modules/reports/reports.module.ts, src/modules/reports/reports.service.spec.ts, src/modules/reports/reports.service.ts, src/modules/reports/router/decorators/api-reports-query.decorator.ts, src/modules/reports/router/decorators/index.ts, src/modules/reports/router/docs/index.ts, src/modules/reports/router/docs/total-items.doc.ts, src/modules/reports/router/dtos/index.ts, src/modules/reports/router/dtos/reports-query.dto.ts, src/modules/reports/router/index.ts, src/modules/reports/router/reports-router.module.ts, src/modules/reports/router/reports.controller.spec.ts, src/modules/reports/router/reports.controller.ts
=> 388 creating reports

src/modules/reports/reports.service.spec.ts, src/modules/reports/reports.service.ts
=> fix(modules/reports/service): fix getting most listened hours

.husky/commit-msg, .husky/pre-commit, src/config/env/env.schema.ts, src/modules/reports/reports.service.spec.ts, src/modules/reports/reports.service.ts, src/modules/reports/router/docs/index.ts, src/modules/reports/router/docs/listening-days.doc.ts, src/modules/reports/router/reports.controller.spec.ts, src/modules/reports/router/reports.controller.ts
=> 403 change reports listening days response type

src/modules/history/tracks/history-tracks.repository.spec.ts, src/modules/history/tracks/history-tracks.repository.ts, src/modules/items/albums/albums.repository.spec.ts, src/modules/items/albums/albums.repository.ts, src/modules/items/artists/artists.repository.spec.ts, src/modules/items/artists/artists.repository.ts, src/modules/items/tracks/tracks.repository.spec.ts, src/modules/items/tracks/tracks.repository.ts, src/modules/users/users.repository.spec.ts, src/modules/users/users.repository.ts
=> 410 remove unused methods from repositories

src/modules/items/albums/album.subscriber.spec.ts, src/modules/items/albums/album.subscriber.ts, src/modules/items/albums/albums.module.ts
=> feat(modules/items/albums): create `AlbumSubscriber` and validate album properties after load

src/modules/stats/router/decorators/api-stats-rigtch-query.decorator.ts, src/modules/stats/router/dtos/stats-rigtch-query.dto.ts, src/modules/stats/router/stats-rigtch.controller.spec.ts, src/modules/stats/router/stats-rigtch.controller.ts, src/modules/stats/stats-rigtch.service.spec.ts, src/modules/stats/stats-rigtch.service.ts
=> feat(modules/stats/rigtch): add offset query parameter

src/modules/reports/reports.service.spec.ts, src/modules/reports/reports.service.ts, src/modules/reports/router/docs/genres-listening-days.doc.ts, src/modules/reports/router/docs/index.ts, src/modules/reports/router/reports.controller.spec.ts, src/modules/reports/router/reports.controller.ts, src/modules/reports/types/picked-history-track.type.ts
=> 397 genres listening days endpoint

src/common/mocks/create-query-builder.factory.mock.ts, src/common/mocks/user.mock.ts, src/migrations/1727274883625-add-user-followers-and-following.ts, src/migrations/1727277320574-add-followers-and-following-count-to-user.ts, src/migrations/all.ts, src/modules/items/images/docs/image.doc.ts, src/modules/items/images/docs/index.ts, src/modules/profiles/docs/index.ts, src/modules/profiles/docs/profile.doc.ts, src/modules/users/controllers/users.controller.spec.ts, src/modules/users/controllers/users.controller.ts, src/modules/users/docs/index.ts, src/modules/users/docs/user.doc.ts, src/modules/users/dtos/create-user.dto.ts, src/modules/users/guards/follow-user.guard.spec.ts, src/modules/users/guards/follow-user.guard.ts, src/modules/users/guards/index.ts, src/modules/users/user.entity.ts, src/modules/users/users.repository.spec.ts, src/modules/users/users.repository.ts
=> 432 implement user followers

src/modules/users/controllers/users.controller.spec.ts, src/modules/users/controllers/users.controller.ts, src/modules/users/users.repository.spec.ts, src/modules/users/users.repository.ts
=> feat(modules/users): create `unfollow` endpoint

src/modules/reports/reports.service.spec.ts, src/modules/reports/reports.service.ts, src/modules/reports/router/reports.controller.spec.ts, src/modules/reports/router/reports.controller.ts, src/modules/users/users.repository.ts
=> 445 move total items from reports to stats

.eslintrc.cjs, src/modules/reports/reports.service.spec.ts, src/modules/reports/reports.service.ts, src/modules/reports/router/reports.controller.spec.ts, src/modules/reports/router/reports.controller.ts
=> 449 refactor reports service totaltracks to remove duplicates and create totalplays endpoint

Dockerfile, src/modules/history/router/history.controller.spec.ts, src/modules/history/router/history.controller.ts, src/modules/items/albums/albums.controller.spec.ts, src/modules/items/albums/albums.controller.ts, src/modules/items/artists/router/artists.controller.spec.ts, src/modules/items/artists/router/artists.controller.ts, src/modules/items/tracks/tracks.controller.spec.ts, src/modules/items/tracks/tracks.controller.ts, src/modules/reports/router/reports.controller.spec.ts, src/modules/reports/router/reports.controller.ts, src/modules/stats/router/stats-rigtch.controller.spec.ts, src/modules/stats/router/stats-rigtch.controller.ts, src/modules/stats/router/stats-spotify.controller.spec.ts, src/modules/stats/router/stats-spotify.controller.ts, src/modules/users/controllers/users-profile.controller.spec.ts, src/modules/users/controllers/users-profile.controller.ts, src/modules/users/controllers/users.controller.spec.ts
=> refactor(controllers): remove cache
